# name: CD
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to server
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           REMOTE_HOST: ${{ secrets.SSH_HOST }}
#           REMOTE_USER: ${{ secrets.SSH_USER }}
#           SOURCE: "./"
#           TARGET: "/home/jayrrod/planning-center-data-pipeline"